// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBztOwKn3HsqaYJECpcz_p_wQou-6Akr6o',
    appId: '1:217903768052:web:02792eb4e59156ad0b99a1',
    messagingSenderId: '217903768052',
    projectId: 'myapp-111ad',
    authDomain: 'myapp-111ad.firebaseapp.com',
    storageBucket: 'myapp-111ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrn2pc10OpUD8YWOmv421QpbXZv3hfYEA',
    appId: '1:217903768052:android:cbf65f22ef2ca59b0b99a1',
    messagingSenderId: '217903768052',
    projectId: 'myapp-111ad',
    storageBucket: 'myapp-111ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu7QRmLKZzV6tgQmX9AXrw_LNQDbeNFHI',
    appId: '1:217903768052:ios:40047758b904f90e0b99a1',
    messagingSenderId: '217903768052',
    projectId: 'myapp-111ad',
    storageBucket: 'myapp-111ad.appspot.com',
    iosBundleId: 'com.codewithduc.myapp.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu7QRmLKZzV6tgQmX9AXrw_LNQDbeNFHI',
    appId: '1:217903768052:ios:30208c5871a1f6e00b99a1',
    messagingSenderId: '217903768052',
    projectId: 'myapp-111ad',
    storageBucket: 'myapp-111ad.appspot.com',
    iosBundleId: 'com.codewithduc.myapp.myapp.RunnerTests',
  );
}
